---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: Continuum Integration
  children:
  - template: Continuum Configuration
    scheduledStartDate: 2020-11-30T12:40:22.575Z
    dueDate: 2020-11-30T13:40:22.577Z
    phases:
    - phase: Configuration
      tasks:
      - name: Create Release Demo Team
        type: continuum.CreateTeam
        continuumServer: Continuum
        team_name: Release Demo
        ^description: Demo Team for Release integration
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK
      - name: Configure Release GitHub
        type: continuum.ConfigureGithub
        continuumServer: Continuum
        githubServer: GitHub xl-release
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK
      - name: Configure JIRA
        type: continuum.ConfigureJira
        continuumServer: Continuum
        jiraServer: Jira Server
        improve_types:
        - Story
        maintain_types:
        - Bug
        - Task
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK
      - name: Configure Project
        type: continuum.CreateProject
        continuumServer: Continuum
        project_name: Digital.ai Release Development
        ^team: Release Demo
        ^description: Source repository for Digital.ai Release
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK
      - name: OK?
        type: xlrelease.GateTask
    riskProfile: Default risk profile
  - template: Runtime Continuum Integration
    description: Runs a sample pipeline in Continuum
    scheduledStartDate: 2020-11-30T12:40:23.776Z
    dueDate: 2020-11-30T13:40:23.776Z
    phases:
    - phase: Continuum
      tasks:
      - name: Configure package manifest
        type: continuum.ProvidePackageManifestData
        continuumServer: Continuum
        package: webstore
        version: "5.0"
        revision_from: 62
        revision_to: 146
      - name: Run a pipeline
        type: continuum.RunAPipeline
        continuumServer: Continuum
        definition: XL Release
        project: XL Release
        group: default
        instance_name: XL Release demo instance
      - name: OK?
        type: xlrelease.GateTask
    scriptUsername: admin
    scriptUserPassword: !value "xlrelease_Release_Runtime_Continuum_Integration_scriptUserPassword"
    riskProfile: Default risk profile
